default_source = "github"
tools = ["claude", "cursor", "copilot", "codex"]
dependencies = [
    {handle = "maragudk/skills/bluesky", type = "skill"},
    {handle = "dsjacobsen/golang-pro", type = "skill"},
    {handle = "madsnorgaard/drupal-expert", type = "skill"},
    {handle = "anthropics/skills/skill-creator", type = "skill"},
    {path = "./skills/migrate-to-skills", type = "skill"},
    {handle = "davila7/claude-code-templates/systematic-debugging", type = "skill"},
    {handle = "obra/superpowers/writing-skills", type = "skill"},
    {path = "./skills/discover-solution-space", type = "skill"},
    {path = "./skills/make-plan", type = "skill"},
    {path = "./skills/code-review", type = "skill"},
    {path = "./skills/make-commit", type = "skill"},
    {path = "./skills/make-release", type = "skill"},
    {path = "./skills/make-research", type = "skill"},
    {handle = "anthropics/skills/canvas-design", type = "skill"},
]

[[source]]
name = "github"
type = "git"
url = "https://github.com/{owner}/{repo}.git"
