default_source = "github"
tools = ["claude", "codex"]
dependencies = [
    {path = "./skills/code-review", type = "skill"},
    {path = "./skills/discover-assumptions", type = "skill"},
    {path = "./skills/discover-codebase-enhancements", type = "skill"},
    {path = "./skills/discover-opportunities", type = "skill"},
    {path = "./skills/discover-outcomes", type = "skill"},
    {path = "./skills/discover-solution-space", type = "skill"},
    {path = "./skills/enhance-docs", type = "skill"},
    {path = "./skills/make-commit", type = "skill"},
    {path = "./skills/make-plan", type = "skill"},
    {path = "./skills/make-release", type = "skill"},
    {path = "./skills/make-research", type = "skill"},
    {path = "./skills/migrate-to-skills", type = "skill"},
    {path = "./skills/skriv-som-kasper", type = "skill"},
]

[[source]]
name = "github"
type = "git"
url = "https://github.com/{owner}/{repo}.git"
